### ISSUE TITLE
Format Date and Time in Noise Level & Trend Box

### ISSUE THREAD

**Issue by mbechtel** [danieltsoukup/noise-dashboard#20]
I think we should format the "Record at" timestamp in the dashboard to a more user-friendly format like:
Recorded at Hour:Minute am/pm on Day of Week, Month Day, Year

Example online:
https://dashboard.tracket.info/locations/753346

How it looks today:
![Screenshot 2024-08-04 at 10-05-20 tRacket Dashboard](https://github.com/user-attachments/assets/c16d0d86-7dc2-4847-be8d-83cc060c575c)

**Comment by danieltsoukup** [comment]
Thanks, Mitch! I would add that the noise level date and  date picker formatting should be consistent too.

- data picker: https://github.com/danieltsoukup/noise-dashboard/blob/main/app/src/app_components.py#L609
- text for level indicator: https://github.com/danieltsoukup/noise-dashboard/blob/main/app/src/app_components.py#L794

**Comment by alphonse-xavier-924** [comment]
Hi @danieltsoukup , I created a pull request https://github.com/danieltsoukup/noise-dashboard/pull/21 for this feature.

**Comment by danieltsoukup** [comment]
Thank you, congrats on the first PR! Updates should be live soon.
