### ISSUE TITLE
Adjust button and trend indicator colors

### ISSUE THREAD

**Issue by danieltsoukup** [danieltsoukup/noise-dashboard#24]
**Describe the bug**
Make sure that the button and trend indicator (% change under the current decibel level) follows the design guide: https://mirayberber.notion.site/22aae19dfc484314860ff92dae1f06fc?v=5ecfe15b0fed4a29bd136e7c241c300b

**To Reproduce**
Visit a location page https://dashboard.tracket.info/locations/756264
<img width="840" alt="image" src="https://github.com/user-attachments/assets/b4f18593-49ec-4e1a-9ca3-8d3660be28ec">

**Expected behavior**
- Use the primary blue for the download button
- Use the secondary-400 for the trend indicator if positive change (orange)
- Use the primary-400 for the trend indicator if negaitve change (blue)

![image](https://github.com/user-attachments/assets/021f08d0-1dcb-4d76-8e93-813ac28b2b11)

![image](https://github.com/user-attachments/assets/be5797b6-47c0-4aee-a30f-055115e85d1b)

**Additional context**
- reset indicator colos here https://github.com/danieltsoukup/noise-dashboard/blob/97584a6e4a3bc2484563efc0b2b31d7feb0bae54/app/src/config.ini#L20
- button https://github.com/danieltsoukup/noise-dashboard/blob/97584a6e4a3bc2484563efc0b2b31d7feb0bae54/app/assets/styles.css#L28

**Comment by alphonse-xavier-924** [comment]
Hi @danieltsoukup , I created a pull request for this update - https://github.com/danieltsoukup/noise-dashboard/pull/28. Please let me know if there are any changes to be made. Thanks.

**Comment by danieltsoukup** [comment]
Awesome! 🔥
