### ISSUE TITLE
Review and Update Fonts Used

### ISSUE THREAD

**Issue by danieltsoukup** [danieltsoukup/noise-dashboard#25]
**Describe the bug**
Our brand guidelines have Inter for main body text & Familjen Grotesk for titles. Texts are replaced with these fonts.
https://mirayberber.notion.site/22aae19dfc484314860ff92dae1f06fc?v=5ecfe15b0fed4a29bd136e7c241c300b

**To Reproduce**
Visit https://dashboard.tracket.info/locations/756264 as an example.

**Expected behavior**
See expected styling of text 
![image](https://github.com/user-attachments/assets/5dd62d4b-f1cd-42e1-8388-15d8646a999e)

**Additional context**
- these styling options should be added to the CSS file `app/assets/styles.css`

**Comment by alphonse-xavier-924** [comment]
Hi @danieltsoukup , I wanted to check with you if this is what you are looking for?

<img width="504" alt="Code" src="https://github.com/user-attachments/assets/8ce851d3-5d3d-4cee-89b6-d1a92d300538">


<img width="941" alt="Font" src="https://github.com/user-attachments/assets/37ab1e41-2d20-498d-9655-5c6c1322de94">

**Comment by danieltsoukup** [comment]
Looks good! One note: I think it would be good to keep the indicator to have the heavier Familijen Grotesk font (while the card body using the Inter otherwise), could we add a style for that? 
<img width="266" alt="image" src="https://github.com/user-attachments/assets/5a76698b-c886-4190-82d0-6550684ac931">

When we return the mean indicator [here](https://github.com/danieltsoukup/noise-dashboard/blob/4307be2003e8f329835c4ca74a3503d2741500ba/app/src/app_components.py#L529), we could use the `style` param of the `Div` to override the card body styling?

**Comment by danieltsoukup** [comment]
I did some testing and turns out that the plotly `Indicator` object cannot be easily styled by CSS so ended up reimplementing it using html and Dash, made the adjustments on the fonts in the CSS and pushed updates to the `development` branch. Thanks @alphonse-xavier-924 the work!
