### ISSUE TITLE
Add navbar links

### ISSUE THREAD

**Issue by danieltsoukup** [danieltsoukup/noise-dashboard#27]
**Is your feature request related to a problem? Please describe.**
Add links on the top navbar to the main tracket pages and 

**Describe the solution you'd like**
All links should open on a new page.
- `Get Tracket` - text link to https://tracket.info/sensor/
- `Noise Map` - text link to https://dashboard.tracket.info/locations
- `About` - text link to https://tracket.info/
- `Donate` - text link to https://opencollective.com/tRacket
- `Log In` - white button linked to TBD. Styling through CSS.

![image](https://github.com/user-attachments/assets/ab0ad6bd-edeb-4d79-a304-f76c6a0abe91)

**Additional context**
- Navbar https://github.com/danieltsoukup/noise-dashboard/blob/97584a6e4a3bc2484563efc0b2b31d7feb0bae54/app/src/app_components.py#L341
- Docs https://dash-bootstrap-components.opensource.faculty.ai/docs/components/navbar/

**Comment by mbechtel** [comment]
Login links for the tRacket Sensor manager should point to:
https://manage.tracket.info/

**Comment by alphonse-xavier-924** [comment]
Hi @danieltsoukup , I have created a pull request https://github.com/danieltsoukup/noise-dashboard/pull/29 for this feature. Please let me know if there are any changes to be made?

![image](https://github.com/user-attachments/assets/40db2f7e-ef0a-4c31-9e40-4096f5487845)

**Comment by danieltsoukup** [comment]
Awesome! Added some comments on the PR.

**Comment by alphonse-xavier-924** [comment]
I have opened a new pull request with the updated changes - https://github.com/danieltsoukup/noise-dashboard/pull/33

**Comment by danieltsoukup** [comment]
Thank you, will be live soon!
